CREATE TABLE sys_tenant
(
    ID         BIGINT NOT NULL COMMENT '租户 ID',
    NAME       VARCHAR(32) COMMENT '租户名称',
    CREATED_BY VARCHAR(32) COMMENT '创建人',
    CREATED_AT DATETIME(6) COMMENT '创建时间',
    UPDATED_BY VARCHAR(32) COMMENT '更新人',
    UPDATED_AT DATETIME(6) COMMENT '更新时间',
    PRIMARY KEY (ID)
) COMMENT = '租户';

CREATE TABLE sys_account
(
    ID              BIGINT      NOT NULL AUTO_INCREMENT COMMENT '用户 ID',
    UID             VARCHAR(64) NOT NULL COMMENT '用户唯一标识',
    TENANT_ID       BIGINT      NOT NULL DEFAULT 0 COMMENT '租户 ID',
    USERNAME        VARCHAR(64) NOT NULL COMMENT '用户名',
    PASSWORD        VARCHAR(128) COMMENT '密码',
    JOB_NUMBER      VARCHAR(64) COMMENT '工号',
    REAL_NAME       VARCHAR(32) COMMENT '真实姓名',
    MOBILE          VARCHAR(11) COMMENT '手机',
    MOBILE_VERIFIED INT(1) COMMENT '手机号是否校验',
    EMAIL           VARCHAR(64) COMMENT '邮箱',
    EMAIL_VERIFIED  INT(1) COMMENT '邮箱是否校验',
    AVATAR          VARCHAR(128) COMMENT '头像',
    STATUS          INT(2) COMMENT '状态',
    CREATED_BY      VARCHAR(32) COMMENT '创建人',
    CREATED_AT      DATETIME(6) COMMENT '创建时间',
    UPDATED_BY      VARCHAR(32) COMMENT '更新人',
    UPDATED_AT      DATETIME(6) COMMENT '更新时间',
    PRIMARY KEY (ID)
) COMMENT = '账号';

CREATE UNIQUE INDEX UK_UID ON sys_account (UID);
CREATE UNIQUE INDEX UK_USERNAME ON sys_account (USERNAME);
CREATE INDEX UK_JOB_NUMBER ON sys_account (JOB_NUMBER);
CREATE INDEX UK_MOBILE ON sys_account (MOBILE);
CREATE INDEX UK_EMAIL ON sys_account (EMAIL);

