server:
  port: 9998
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:13306/unity
    username: root
    password: root!@@&
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: embedded
      encoding: utf-8
      continue-on-error: on
      schema-locations:
        - classpath:META-INF/schema.sql
        - classpath:META-INF/data.sql
  security:
    oauth2:
      authorizationserver:
        multiple-issuers-allowed: false
      # 联合身份认证提供商客户端
      client:
        registration:
          dingtalk:
            client-id: dingopfniakkw72klkjv
            client-secret: 6Il0DuPZPPIr-OG03uMrnqDNu_o03tpIkK03ScpuEPP6NAw7J52D0LWPvTjRf4BR
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: corpid
          github:
            provider: github
            client-id: db3bd3536a1d3163acf9
            client-secret: 45e9229144cfd3e083ee6994f4719c31bc553cf5
        provider:
          dingtalk:
            authorization-uri: https://login.dingtalk.com/oauth2/auth
            token-uri: https://api.dingtalk.com/v1.0/oauth2/userAccessToken
            user-info-uri: https://api.dingtalk.com/v1.0/contact/users/me
            user-info-authentication-method: header
            user-name-attribute: nick
logging:
  level:
    root: warn
    org.springframework: info
    org.springframework.security: info
    org.springframework.security.oauth2: trace
    org.springframework.security.authorization: trace
    org.springframework.security.authentication: trace
    org.codecrafterslab.unity.oauth2: trace
management:
  endpoint:
    health:
      probes:
        enabled: true
