name: Publish Unity Gradle Plugin
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'gradle-plugins/gradle.properties'
jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Publish to AliYun
        run: ./gradlew :gradle-plugins:publishAllPublicationsToAliYunRepository
        env:
          DEV_OPTS_ALIYUN_USERNAME: ${{ secrets.DEV_OPTS_ALIYUN_USERNAME }}
          DEV_OPTS_ALIYUN_PASSWORD: ${{ secrets.DEV_OPTS_ALIYUN_PASSWORD }}